# -*- coding: utf-8 -*-
"""Transformer HIT 1 - HIT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbvvDxeBXSDeLlaYu1dOxbudqOG4JUGt
"""

import pandas as pd
import numpy as np

df = pd.read_csv("data.csv")
final_df = pd.DataFrame(columns=["id", "title", "body", "question1","answer1_1", "answer1_2", "answer1_3","question2","answer2_1", "answer2_2", "answer2_3", 
                                 "question3","answer3_1", "answer3_2", "answer3_3","position_ans_1","position_ans_2","position_ans_3"])
df.head(9)

import random

def randomizer1():
  array = [4,5,6]
  answer = random.choice(array)
  array.remove(answer)
 
  incorrect1 = array[0]
  incorrect2 = array[1]
  return answer, incorrect1, incorrect2

def randomizer2():
  array = [8,9,10]
  answer = random.choice(array)
  array.remove(answer)
 
  incorrect1 = array[0]
  incorrect2 = array[1]
  return answer, incorrect1, incorrect2

def randomizer3():
  array = [12,13,14]
  answer = random.choice(array)
  array.remove(answer)
 
  incorrect1 = array[0]
  incorrect2 = array[1]
  return answer, incorrect1, incorrect2

def addRow(df,ls):
    numEl = len(ls)
    newRow = pd.DataFrame(np.array(ls).reshape(1,numEl), columns = list(df.columns))
    df = df.append(newRow, ignore_index=True)
    return df

unique_ids = df['id'].unique()
length_ids = len(unique_ids)
print(unique_ids)
for i in unique_ids:
  print(i)
  rows = df.loc[df['id'] == i]
  try:
    randomList = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1]
    id = rows.loc[0,]["id"]
    randomList[0] = id
    title = rows.loc[0,]["title"]
    randomList[1] = title
    body = rows.loc[0,]["body"]
    randomList[2] = body
      
    poscorrect1, poswrong1_1, poswrong1_2 = randomizer1()
    poscorrect2, poswrong2_1, poswrong2_2 = randomizer2()
    poscorrect3, poswrong3_1, poswrong3_2 = randomizer3()

    question1 = rows.loc[0,]["question"]
    randomList[3] = question1
    answer1 = rows.loc[0,]["answer"]
    wrong1_1 = rows.loc[0,]["wrong_answer_1"]
    wrong1_2 = rows.loc[0,]["wrong_answer_2"]

    randomList[15] = poscorrect1
    randomList[poswrong1_1] = wrong1_1
    randomList[poswrong1_2] = wrong1_2

    question2 = rows.loc[1,]["question"]
    randomList[7] = question2
    answer2 = rows.loc[1,]["answer"]
    wrong2_1 = rows.loc[1,]["wrong_answer_1"]
    wrong2_2 = rows.loc[1,]["wrong_answer_2"]


    randomList[16] = poscorrect2
    randomList[poswrong2_1] = wrong2_1
    randomList[poswrong2_2] = wrong2_2

    question3 = rows.loc[2,]["question"]
    randomList[11] = question3
    answer3 = rows.loc[2,]["answer"]
    wrong3_1 = rows.loc[2,]["wrong_answer_1"]
    wrong3_2 = rows.loc[2,]["wrong_answer_2"]


    randomList[17] = poscorrect3
    randomList[poswrong3_1] = wrong3_1
    randomList[poswrong3_2] = wrong3_2
    final_df = addRow(final_df, randomList)

  except KeyError:
         continue

final_df

final_df.to_csv("output.csv")







i = 2
some_counter = 0
while some_counter < i:
    some_counter += 1
    rows = df.loc[df['id'] == i]
    try:
        randomList = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1]
        id = rows.loc[0,]["id"]
        randomList[0] = id
        title = rows.loc[0,]["title"]
        randomList[1] = title
        body = rows.loc[0,]["body"]
        randomList[2] = body
            
        poscorrect1, poswrong1_1, poswrong1_2 = randomizer1()
        poscorrect2, poswrong2_1, poswrong2_2 = randomizer2()
        poscorrect3, poswrong3_1, poswrong3_2 = randomizer3()

        question1 = rows.loc[0,]["question"]
        randomList[3] = question1
        answer1 = rows.loc[0,]["answer"]
        wrong1_1 = rows.loc[0,]["wrong_answer_1"]
        wrong1_2 = rows.loc[0,]["wrong_answer_2"]

        randomList[15] = poscorrect1
        randomList[poswrong1_1] = wrong1_1
        randomList[poswrong1_2] = wrong1_2

        question2 = rows.loc[1,]["question"]
        randomList[7] = question2
        answer2 = rows.loc[1,]["answer"]
        wrong2_1 = rows.loc[1,]["wrong_answer_1"]
        wrong2_2 = rows.loc[1,]["wrong_answer_2"]


        randomList[16] = poscorrect2
        randomList[poswrong2_1] = wrong2_1
        randomList[poswrong2_2] = wrong2_2

        question3 = rows.loc[2,]["question"]
        randomList[11] = question3
        answer3 = rows.loc[2,]["answer"]
        wrong3_1 = rows.loc[2,]["wrong_answer_1"]
        wrong3_2 = rows.loc[2,]["wrong_answer_2"]


        randomList[17] = poscorrect3
        randomList[poswrong3_1] = wrong3_1
        randomList[poswrong3_2] = wrong3_2
        final_df = addRow(final_df, randomList)

    except KeyError:
        continue